export const LOAD_PROFILE = "LOAD_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const UNFOLLOW = "UNFOLLOW";
export const FOLLOW = "FOLLOW";
export const GET_ERRORS = "GET_ERRORS";
export const LOADING_POSTS = "LOADING_POSTS"
export const GET_POSTS = "GET_POSTS"
export const ADD_POST = "ADD_POST"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const DELETE_POST ="DELETE_POST"
export const YOUR_POSTS = "YOUR_POST"
